### ISSUE TITLE
discuss function documentation

### ISSUE THREAD

**Issue by Fesch-star** [Fesch-star/CM_analysis#18]
Docstrings can be added to functions using rogygen2, see:

https://carpentries-incubator.github.io/lesson-R-packaging/documentation.html#documenting-your-functions-with-roxygen2

**Comment by jelletreep** [comment]
- [ ] Are all docstrings now clean and clear?
- [ ] Should the examples show output in the generated documentation, if yes what data do we use?
- [x] There are some inconsistencies (two words or lengthy descriptions) in the display of the functions [here](https://fesch-star.github.io/cognitivemapr/reference/index.html), we should decide on what we want to display there
