### ISSUE TITLE
look into CITATION.cff file

### ISSUE THREAD

**Issue by nehamoopen** [Fesch-star/CM_analysis#26]

**Comment by Fesch-star** [comment]
I added information, not sure if this is now finished

**Comment by nehamoopen** [comment]
The current CITATION.cff file is not passing validation checks using the `cffr` package (with the `cff_validate(x = "CITATION.cff", verbose = TRUE` function). 

The error message wasn't very clear: `Error in yaml.load(string, error.label = error.label, ...) : 
  (CITATION.cff) Scanner error: while scanning a simple key at line 12, column 1 could not find expected ':' at line 13, column 1`
  
  I assume it had to do with a `:` in the abstract, but removing it did not resolve the error.
  
  I started using the cffinit website to reconstruct the CITATION.cff and this what I got that passes validation checks:

```
# This CITATION.cff file was generated with cffinit.
# Visit https://bit.ly/cffinit to generate yours today!

cff-version: 1.2.0
title: 'cognitivemapr: Functions for Cognitive Mapping Analysis'
message: >-
  If you use this software, please cite it using the
  metadata from this file.
type: software
authors:
  - given-names: van Esch
    family-names: Femke
    email: f.a.w.j.vanesch@uu.nl
    orcid: 'https://orcid.org/0000-0002-2559-3127'
    affiliation: Utrecht University
  - given-names: Treep
    family-names: Jelle
    email: h.j.treep@uu.nl
    affiliation: Utrecht University
    orcid: 'https://orcid.org/0000-0003-3196-7954'
  - given-names: Moopen
    family-names: Neha
    email: n.moopen@uu.nl
    affiliation: Utrecht University
    orcid: 'https://orcid.org/0000-0003-1412-4402'
  - given-names: Snellens
    family-names: Jeroen
    email: snellens@gmail.com
repository-code: 'https://github.com/Fesch-star/cognitivemapr'
abstract: >-
  Cognitive mapping is a method specifically designed to
  study belief systems

  and has several advantages over other methods. The goal of
  the package is to reduce

  the initial (time) investment needed to start using the
  method. The package provides

  several functions to conduct the type of cognitive mapping
  analysis as described

  in the article - 'How to ‘measure’ Ideas. Introducing the
  method of cognitive mapping

  to the domain of ideational policy studies’ as published
  in 2024 in the Journal

  of European Public Policy by Femke Van Esch and Jeroen
  Snellens.
```

It doesn't seem to be possible to distinguish between authors and contributors, I checked the cff schema guide for this. We can still add a contact and keywords, plus links to other sites and resources.

**Comment by Fesch-star** [comment]
added jeroen's Orchid - this may be ready to close??

**Comment by nehamoopen** [comment]
A PR has been opened for this issue, it's more or less ready to go. There are some additional fields we could include in the CITATION.cff file before release:

- [x] keywords
- [x] references

@Fesch-star : are there specific keywords or references (for example, articles) you would like to include?
 
Following the first release, we could add the following as well:

- [x] doi

**Comment by nehamoopen** [comment]
The CITATION.cff file needs to be reviewed, it seems that first and last names are flipped in the citation.

**Comment by jelletreep** [comment]
#54

**Comment by nehamoopen** [comment]
Added Zenodo DOI as well, gonna close the issue :)
