### ISSUE TITLE
update DESCRIPTION file

### ISSUE THREAD

**Issue by jelletreep** [Fesch-star/CM_analysis#28]
I have inserted a title, probably can be improved (should be maximum one line and Using Cases)

- [x]  add Author information (email, role, DOI)
- [x]  add description (one paragraph)

See: [https://r-pkgs.org/description.html](https://r-pkgs.org/description.html) for detailed instructions and conventions

**Comment by Fesch-star** [comment]
@jelletreep: I tried to be brief and clear in the description. Maybe you could check whether it is adequate

**Comment by jelletreep** [comment]
Yes, this is OK! We still need to add some author information (ORCIDs)
