### ISSUE TITLE
Revise README

### ISSUE THREAD

**Issue by jelletreep** [Fesch-star/CM_analysis#3]
The readme still needs some information to be added.

I think a short tutorial (tutorial.md) that demonstrates the use and output of the functions based on the example data in the data folder would be very useful

**Comment by Fesch-star** [comment]
@jelletreep I am not sure what to add to this file. We have a separate tutorial. What else should we put in the readme?

**Comment by jelletreep** [comment]
@Fesch-star , we have to consider different ways that people find this package. It is good practice to always have a README in GitHub, while the tutorial is meant for elaborate information about using the package, the readme is a landing page for people that find this project via github. The readme is brief and aims to provide information about what can be found inside the repository. It should have a short description, status information, contact information, installation information, link to the tutorial site and information on how to contribute to the repository. For the rest it is flexible, some visuals about what your package does (maybe a cognitive map?) always work well. See e.g. the Readme here as example: [https://github.com/sodascience/metasyn](https://github.com/sodascience/metasyn)

**Comment by Fesch-star** [comment]
I sort of did this - but it does not show on github. Also I think we need a different citation (not to the article, but to the software).
