### ISSUE TITLE
solve the fail errors I created this week - see email 

### ISSUE THREAD

**Issue by Fesch-star** [Fesch-star/CM_analysis#36]

**Comment by jelletreep** [comment]
- [ ] fix image vignette
- [ ] improve layout equations

**Comment by Fesch-star** [comment]
@jelletreep: mmm, I have broken the package again. It happened after the "clean up todo ...." commit  that I did (second to last commit on March 8). I deleted some broken and unnecessary stuff from the package and worked on a second tutorial. Sorry, hope I did not break it too badly.

**Comment by jelletreep** [comment]
Will look at it next week!

**Comment by Fesch-star** [comment]
done
