### ISSUE TITLE
create a doi (or something like it) for the package

### ISSUE THREAD

**Issue by Fesch-star** [Fesch-star/CM_analysis#39]

**Comment by nehamoopen** [comment]
Neha will coordinate with Femke to integrate GitHub & Zenodo. This has to happen before the first package release, so Zenodo can detect it when it becomes available.

**Comment by nehamoopen** [comment]
@Fesch-star : I think we set up the GitHub x Zenodo integration and made sure this repo was being tracked for releases? If yes, you can go ahead and close this issue 😊
