### ISSUE TITLE
add dataset documentation

### ISSUE THREAD

**Issue by jelletreep** [Fesch-star/CM_analysis#41]
[https://fesch-star.github.io/cognitivemapr/reference/rutte_p2_edgelist.html](https://fesch-star.github.io/cognitivemapr/reference/rutte_p2_edgelist.html)
[https://fesch-star.github.io/cognitivemapr/reference/rutte_p2_nodelist.html](https://fesch-star.github.io/cognitivemapr/reference/rutte_p2_nodelist.html)

**Comment by nehamoopen** [comment]
Neha will make a start using one of the codebook packages and Femke can add on it.

**Comment by jelletreep** [comment]
I think it can be done with docstrings? 
Here is the file that is used to generate above html files:
https://github.com/Fesch-star/cognitivemapr/blob/main/R/rutte_data.R

**Comment by nehamoopen** [comment]
@Fesch-star will provide a few lines describing the dataset(s) in general. @nehamoopen will start working out the documentation file using docstrings (for the specific columns).

**Comment by nehamoopen** [comment]
A PR has been opened for this issue, it's more or less ready to go. The documentation can be improved slightly by:

- [X] giving a better introduction to the dataset, @Fesch-star : could you provide a few lines for this? 
- [X] specifying the data types of each variable

**Comment by nehamoopen** [comment]
The dataset documentation needs to be reviewed. There's some doubled text/sections...

**Comment by nehamoopen** [comment]
This has been in addressed in the development and a PR has been opened.
