### ISSUE TITLE
check images in Tutorial

### ISSUE THREAD

**Issue by jelletreep** [Fesch-star/CM_analysis#42]
There was a failing image, I am not sure where the file is or if it should be replaced by a new image?

**Comment by jelletreep** [comment]
- [x] Remove this from the text in the tutorial: 

## change the figure to one showing the true evaluations & rewrite the text

**Comment by nehamoopen** [comment]
clarification: this is in the general `cognitivemapr` tutorial and refers to the colorful map/network image

**Comment by jelletreep** [comment]
- [x] Improve layout equations, should the \ be in there? And change the symbols in the legend to have the same appearance as in the equations

**Comment by Fesch-star** [comment]
reinserted the right image, deleted the text and / . I could not get the legend into the same format as the equation (adding $$ distorts the layout)
