### ISSUE TITLE
update README.md

### ISSUE THREAD

**Issue by nehamoopen** [Fesch-star/CM_analysis#51]
The README could do with an update, this can happen after the first release :)

**Comment by Fesch-star** [comment]
citation need updating

**Comment by nehamoopen** [comment]
add DOI badge as well :)

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.11068150.svg)](https://doi.org/10.5281/zenodo.11068150)

**Comment by nehamoopen** [comment]
done!
