### ISSUE TITLE
v0.1.1

### ISSUE THREAD

**Issue by nehamoopen** [Fesch-star/CM_analysis#53]
- [x] check the logo
- [x] review dataset documentation #41 
- [x] review table of contents in tutorial
- [x] review CITATION.cff file #26 
- [x] just check pkgdown website...

**Comment by jelletreep** [comment]
First and lastnames were swapped in the .cff file. And we had to create new favicons from the logo. See #54

**Comment by jelletreep** [comment]
I think the ToC in the vignettes is also fixed. I also changed the titles a tiny bit, feel free to change it back if you disagree @Fesch-star . See the changes in #54

**Comment by jelletreep** [comment]
The double links seem to be fixed as well, not sure what was causing that

**Comment by nehamoopen** [comment]
Done!
